name: spoonacular_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+2
  # http Allows us to send requests to API to get data
  webview_flutter: ^0.3.18+1
  # webview allows us to view web pages within our app

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.1.4

  # Toast
  fluttertoast: ^3.1.3

  # Carousel
  carousel_slider: ^1.4.1

  # Database
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4
  firebase_database:

  # intl calendar
  intl:

  # Font awesome flutter
  font_awesome_flutter: ^8.7.0

  # Search bar
  flappy_search_bar: 1.4.1

  logger: ^0.7.0+2

  flutter_screenutil: ^0.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image_01.png
    - assets/image_02.png
    - assets/logo.png
    - assets/images/arrow.png
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/logo.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf